# Site Settings
title: London Regen Jobs
email: info@londonregenjobs
description: >
  A guide to getting started with Jekyll.
baseurl:
url: "http://londonregenjobs.github.io"
twitter_username: londonregenjobs
github_username:  londonregenjobs
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']

# Markdown handling
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown

kramdown:
  input: GFM
